### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by vitalii-kushnirenko** [vitalii-kushnirenko/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by katya-pidpala** [comment]
**DEADPOOL**
    • https://www.instagram.com/vancityreynolds/
    • https://twitter.com/vancityreynolds
    • https://www.facebook.com/VancityReynolds
