### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by vitalii-kushnirenko** [vitalii-kushnirenko/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by katya-pidpala** [comment]
**EXPERIENCE**

1991 
Created by artist/writer Rob Liefeld and writer Fabian Nicieza, Deadpool made his first appearance in the pages of The New Mutants #98 cover dated February 1991. According to Nicieza, Liefeld came up with the character's visual design and name, and Nicieza himself came up with the character's speech mannerisms.

1993 
In 1993, the character received his own miniseries, titled The Circle Chase, written by Fabian Nicieza and pencilled by Joe Madureira.

1994
It was a relative success and Deadpool starred in a second, self-titled miniseries written in 1994 by Mark Waid, pencilled by Ian Churchill, and inked by Jason Temujin Minor and Bud LaRosa. Waid later commented, "Frankly, if I'd known Deadpool was such a creep when I agreed to write the mini-series, I wouldn't have done it. Someone who hasn't paid for their crimes presents a problem for me."

1997
In 1997, Deadpool was given his own ongoing title, initially written by Joe Kelly, with then-newcomer Ed McGuinness as an artist. Deadpool became an action comedy parody of the cosmic drama, antihero-heavy comics of the time. 

2002
For a time, writers who followed generally ignored the fourth wall entirely, until Gail Simone took over with issue #65. Her version is remembered for the frequent use of the "little yellow boxes."[27] Deadpool lasted until issue #69, at which point it was relaunched as a new title with a similar character called Agent X.

2004
Deadpool's next starring appearance came in 2004 with the launch of Cable & Deadpool written by Fabian Nicieza, where Deadpool became partnered with his former enemy, Cable, teaming up in various adventures. 

2009
Another ongoing Deadpool series, Deadpool: Merc with a Mouth launched in July 2009, written by Victor Gischler, with art by Bong Dazo. In it Deadpool teams with Headpool from Marvel Zombies 3 and 4.

A special anniversary issue titled Deadpool #900 was released in October 2009. It features stories written by several authors, with the main feature written by the original Deadpool series writer Joe Kelly and drawn by Deadpool's creator Rob Liefeld. A third Deadpool ongoing series, Deadpool Team-Up, launched in November 2009 (with issue numbers counting in reverse starting with issue #899), written by Fred Van Lente, with art by Dalibor Talajic. This series features Deadpool teaming up with different heroes from the Marvel Universe in each issue, such as Hercules. Deadpool also joined the cast of the new Uncanny X-Force team.

2010
Another Deadpool series by Gischler titled Deadpool Corps was released in April 2010. Besides Deadpool himself, this series featured alternate versions of Deadpool, including Lady Deadpool (who debuted in Deadpool: Merc with a Mouth #7), Headpool (the Marvel Zombies universe incarnation, now reduced to a severed head), and two new characters; Kidpool, a child, and Dogpool, a dog.

2016
Deadpool is a 2016 American superhero film based on the Marvel Comics character of the same name. Distributed by 20th Century Fox, it is the eighth film in the X-Men film series. Directed by Tim Miller from a screenplay by Rhett Reese and Paul Wernick, it stars Ryan Reynolds in the title role alongside Morena Baccarin, Ed Skrein, T. J. Miller, Gina Carano, and Brianna Hildebrand. In the film, Wade Wilson hunts the man who gave him mutant abilities and a scarred physical appearance, becoming the beloved antihero Deadpool.

2018
Deadpool 2 is a 2018 American superhero film based upon the Marvel Comics character Deadpool. It is the eleventh installment in the X-Men film series, and is the sequel to 2016's Deadpool. The film was directed by David Leitch from a screenplay by Rhett Reese, Paul Wernick, and Ryan Reynolds, who stars in the title role alongside Josh Brolin, Morena Baccarin, Julian Dennison, Zazie Beetz, T.J. Miller, Brianna Hildebrand, and Jack Kesy. In the film, Deadpool forms the X-Force to protect a young mutant from the time-traveling soldier Cable.
